### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by david-schopf** [render-oss/homebrew-render#5]
Last 15 lines from /Users/david.schopf/Library/Logs/Homebrew/render/01.make:
Download https://deno.land/std@0.129.0/node/_core.ts
Download https://deno.land/std@0.129.0/node/_process/exiting.ts
Download https://deno.land/std@0.129.0/node/_fixed_queue.ts
Download https://deno.land/std@0.129.0/node/internal/buffer.mjs
Download https://deno.land/std@0.129.0/node/internal_binding/_utils.ts
Download https://deno.land/std@0.129.0/node/internal_binding/buffer.ts
Download https://deno.land/std@0.129.0/encoding/base64.ts
Download https://deno.land/std@0.129.0/encoding/base64url.ts
Download https://deno.land/std@0.129.0/node/internal_binding/string_decoder.ts
Download https://deno.land/std@0.129.0/node/internal_binding/_node.ts
error: The source code is invalid, as it does not match the expected hash in the lock file.
  Specifier: https://esm.sh/v86/ajv-formats@2.1.1
  Lock file: deps-lock.json
make[1]: *** [deps] Error 10
make: *** [build-local] Error 2

**Comment by zavbala** [comment]
Oh boy, same here :(

**Comment by remast** [comment]
I have that issue too...

**Comment by robdimarco-render** [comment]
Fix has been applied. You should be able to run 

```
brew tap render-oss/render
brew install render
```

and have it succeed now.
